apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-be
  namespace: todo
  labels:
    app: todo
    tier: be
spec:
  selector:
    matchLabels:
      app: todo
      tier: be
      type: container
  replicas: 1
  template:
    metadata:
      labels:
        app: todo
        tier: be
        type: container
    spec:
      containers:
        - name: todo-be
          image: todo-zulu-alpine-jre-11:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
