kind: Service
apiVersion: v1
metadata:
  name: todo-be
spec:
  selector:
    app: todo-be
  ports:
    - protocol: TCP
      port: 8081
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-be
spec:
  selector:
    matchLabels:
      app: todo-be
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-be
    spec:
      containers:
        - name: todo-be
          image: jtonic/todo-zulu-alpine-jre-11:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
