apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-fe-dep
  labels:
    app: todo
    tier: fe
spec:
  selector:
    matchLabels:
      app: todo
      tier: fe
      type: container
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: todo
        tier: fe
        type: container
    spec:
      containers:
        - name: todo-fe
          image: todo-fe-alpine-ngnix-vue:latest
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 2
              memory: 500Mi
          imagePullPolicy: Never
          ports:
            - containerPort: 80
