apiVersion: v1
kind: Service
metadata:
  name: todo-fe
spec:
  type: NodePort
  selector:
    app: todo-fe
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-fe
spec:
  selector:
    matchLabels:
      app: todo-fe
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: todo-fe
    spec:
      containers:
        - name: todo-fe
          image: jtonic/todo-fe:v1
          resources:
            requests:
              cpu: 100m
              memory: 300Mi
            limits:
              cpu: 2
              memory: 500Mi
          imagePullPolicy: Always
