apiVersion: v1
kind: Service
metadata:
  namespace: todo
  name: todo-fe
  labels:
    app: todo
    tier: fe
spec:
  type: NodePort
  selector:
    app: todo
    tier: fe
    type: container
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
